=== ageru666/Lab2_oop_sem5/beers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Beers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Beer" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Type" type="xs:string"/>
                            <xs:element name="Alcoholic" type="xs:boolean"/>
                            <xs:element name="Manufacturer" type="xs:string"/>
                            <xs:element name="Ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Ingredient" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Chars">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Char" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Turnover" type="xs:integer"/>
                                                    <xs:element name="Transparency" type="xs:integer"/>
                                                    <xs:element name="Filtered" type="xs:boolean"/>
                                                    <xs:element name="Calories" type="xs:integer"/>
                                                    <xs:element name="Dispensing">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Volume" type="xs:integer"/>
                                                                <xs:element name="Material" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ageru666/Lab2_oop_sem5/src/beers.xml
<?xml version="1.0" encoding="UTF-8"?>
<Beers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../beers.xsd">
    <Beer>
        <Name>Stout</Name>
        <Type>Dark</Type>
        <Alcoholic>true</Alcoholic>
        <Manufacturer>Example Brewery</Manufacturer>
        <Ingredients>
            <Ingredient>Water</Ingredient>
            <Ingredient>Malt</Ingredient>
            <Ingredient>Hops</Ingredient>
        </Ingredients>
        <Chars>
            <Char>
                <Turnover>3000</Turnover>
                <Transparency>80</Transparency>
                <Filtered>true</Filtered>
                <Calories>200</Calories>
                <Dispensing>
                    <Volume>500</Volume>
                    <Material>Glass</Material>
                </Dispensing>
            </Char>
        </Chars>
    </Beer>
    <Beer>
        <Name>IPA</Name>
        <Type>India Pale Ale</Type>
        <Alcoholic>true</Alcoholic>
        <Manufacturer>Another Brewery</Manufacturer>
        <Ingredients>
            <Ingredient>Water</Ingredient>
            <Ingredient>Malt</Ingredient>
            <Ingredient>Hops</Ingredient>
        </Ingredients>
        <Chars>
            <Char>
                <Turnover>4000</Turnover>
                <Transparency>75</Transparency>
                <Filtered>true</Filtered>
                <Calories>220</Calories>
                <Dispensing>
                    <Volume>330</Volume>
                    <Material>Bottle</Material>
                </Dispensing>
            </Char>
        </Chars>
    </Beer>
    <Beer>
        <Name>Pilsner</Name>
        <Type>Light</Type>
        <Alcoholic>true</Alcoholic>
        <Manufacturer>Yet Another Brewery</Manufacturer>
        <Ingredients>
            <Ingredient>Water</Ingredient>
            <Ingredient>Malt</Ingredient>
            <Ingredient>Hops</Ingredient>
        </Ingredients>
        <Chars>
            <Char>
                <Turnover>3500</Turnover>
                <Transparency>85</Transparency>
                <Filtered>true</Filtered>
                <Calories>180</Calories>
                <Dispensing>
                    <Volume>500</Volume>
                    <Material>Can</Material>
                </Dispensing>
            </Char>
        </Chars>
    </Beer>
</Beers>
